### PR TITLE
Bump zfp to 1.0.1 and change to submodule

### PR DESCRIPTION
**Pull request by LDeakin**

### CODE REVIEW

**Comment by jvo203** [comment]
Hi, thanks for the PR. Before merging I have a quick question: what is the rationale behind making it into a submodule?

**Comment by LDeakin** [comment]
- More transparent: I can verify that the `zfp` source is set to the [1.01 release](https://github.com/LLNL/zfp/releases/tag/1.0.1)
   - I cannot verify that your `zfp-1.0.0` directory is indeed the 1.0.0 release and not a dev version without checking it out and doing a diff
 - Updating to a new release is trivial
 - Reduces the size of this repository, because you don't track changes to `zfp` directly, just a ref to a commit

**Comment by jvo203** [comment]
OK I see, thanks. I'll merge it, test it and publish a new release on crates.io shortly.

**Comment by jvo203** [comment]
As it stands the project no longer builds after merging the recent changes. Will need to think of how to fix it:
```
   Compiling zfp-sys v0.1.14 (/Users/chris/projects/zfp-sys)
error: failed to run custom build command for `zfp-sys v0.1.14 (/Users/chris/projects/zfp-sys)`

Caused by:
  process didn't exit successfully: `/Users/chris/projects/zfp-sys/target/debug/build/zfp-sys-49f89a5898665dae/build-script-build` (exit status: 101)
  --- stdout
  CMAKE_TOOLCHAIN_FILE_aarch64-apple-darwin = None
  CMAKE_TOOLCHAIN_FILE_aarch64_apple_darwin = None
  HOST_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_GENERATOR_aarch64-apple-darwin = None
  CMAKE_GENERATOR_aarch64_apple_darwin = None
  HOST_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  CMAKE_PREFIX_PATH_aarch64-apple-darwin = None
  CMAKE_PREFIX_PATH_aarch64_apple_darwin = None
  HOST_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_aarch64-apple-darwin = None
  CMAKE_aarch64_apple_darwin = None
  HOST_CMAKE = None
  CMAKE = None
  running: cd "/Users/chris/projects/zfp-sys/target/debug/build/zfp-sys-fe8ee8666d306a6b/out/build" && CMAKE_PREFIX_PATH="" "cmake" "/Users/chris/projects/zfp-sys/zfp" "-DCMAKE_OSX_ARCHITECTURES=arm64" "-DCMAKE_INSTALL_PREFIX=/Users/chris/projects/zfp-sys/target/debug/build/zfp-sys-fe8ee8666d306a6b/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -arch arm64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -arch arm64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC -arch arm64" "-DCMAKE_ASM_COMPILER=/usr/bin/cc" "-DCMAKE_BUILD_TYPE=Debug"

  --- stderr
  CMake Warning:
    Ignoring extra path from command line:

     "/Users/chris/projects/zfp-sys/zfp"


  CMake Error: The source directory "/Users/chris/projects/zfp-sys/zfp" does not appear to contain CMakeLists.txt.
  Specify --help for usage, or press the help button on the CMake GUI.
  thread 'main' panicked at /Users/chris/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cmake-0.1.50/src/lib.rs:1098:5:

  command did not execute successfully, got: exit status: 1

  build script failed, must exit now
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by LDeakin** [comment]
You need to check out the submodule. `git submodule update --init --recursive`

**Comment by jvo203** [comment]
Ah OK, I'm not familiar with submodules! The zfp folder was empty.

**Comment by LDeakin** [comment]
No worries! For future reference, the procedure to update zfp is:
1. Checkout the `zfp` update
```bash
# in zfp-sys/zfp
git fetch
git checkout 1.X.Y
```
2. Test the update
3. Commit the update to to `zfp-sys`
```bash
# in zfp-sys
git add zfp
git commit -m "Bump zfp to 1.X.Y"
```

Also, since this repository now uses a submodule, [it should be cloned with the `--recurse-submodules` flag](https://git-scm.com/docs/git-clone#Documentation/git-clone.txt---recurse-submodulesltpathspecgt). Otherwise, the submodule directory will be empty as you noticed.

**Pull request merged**
